services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: mac-mini-media
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - tailscale-state:/var/lib/tailscale
      - ./ts-config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped

  navidrome:
    image: deluan/navidrome:latest
    network_mode: service:tailscale
    depends_on:
      - tailscale
    user: 501:20 # should be owner of volumes
    volumes:
      - ${NAVIDROME_DATA_PATH}:/data
      - ${MUSIC_PATH}:/music:ro
    restart: unless-stopped

  filebrowser:
    image: gtstef/filebrowser:beta
    network_mode: service:tailscale
    depends_on:
      - tailscale
    volumes:
      - ${FILES_PATH}:/folder
      - ./filebrowser-data:/home/filebrowser/data
    restart: unless-stopped

  glances:
    image: nicolargo/glances:latest
    network_mode: service:tailscale
    depends_on:
      - tailscale
    pid: host
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /proc:/host/proc:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped


volumes:
  tailscale-state:
