server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Health checks only
    location = /_health/navidrome {
        proxy_pass http://127.0.0.1:4533/ping;
    }

    location = /_health/filebrowser {
        proxy_pass http://127.0.0.1:8080/health;
    }

    location = /_health/jellyfin {
        proxy_pass http://127.0.0.1:8096/health;
    }

    location = /_health/glances {
        proxy_pass http://127.0.0.1:61208/;
    }

    # Redirect /<service> to the corresponding service port
    # location = /navidrome {
    #     return 302 $scheme://$host:4533/;
    # }
    # location = /filebrowser {
    #     return 302 $scheme://$host:8080/;
    # }
    # location = /jellyfin {
    #     return 302 $scheme://$host:8096/;
    # }
    location = /glances {
        return 302 $scheme://$host:61208/;
    }

    # reverse proxy for each service
    location /navidrome/ {
        proxy_pass http://127.0.0.1:4533/navidrome/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }    

    location /jellyfin/ {
        proxy_pass http://127.0.0.1:8096/jellyfin/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /filebrowser/ {
        proxy_pass http://127.0.0.1:8080/filebrowser/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
