services:
  landing2:
    build: .
    command: ["uv", "run", "flask", "--app", "app", "run", "--host=0.0.0.0", "--port=81", "--debug"]
    environment:
      - FLASK_DEBUG=1
    volumes:
      - ./app.py:/app/app.py
      - ./templates:/app/templates
    ports:
      - "8888:8888"
